ServerName localhost

LoadModule deflate_module /usr/local/apache2/modules/mod_deflate.so
LoadModule proxy_module /usr/local/apache2/modules/mod_proxy.so
LoadModule proxy_fcgi_module /usr/local/apache2/modules/mod_proxy_fcgi.so
LoadModule rewrite_module /usr/local/apache2/modules/mod_rewrite.so

<IfModule unixd_module>
    User web
    Group web
</IfModule>

<VirtualHost *:80>
    DocumentRoot /var/www/html/public/

    <FilesMatch \.php$>
        SetHandler "proxy:fcgi://app:9000"
    </FilesMatch>

    <Directory /var/www/html/public/>
        DirectoryIndex index.php
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    CustomLog /proc/self/fd/1 combined
    ErrorLog /proc/self/fd/2
</VirtualHost>
